const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getAllProjects: (fila) => ipcRenderer.invoke('projects:getAll', fila),
  getFila: () => ipcRenderer.invoke('fila:get'),
  getSavedQueues: () => ipcRenderer.invoke('fila:getSavedQueues'),
  createFila: (payload) => ipcRenderer.invoke('fila:create', payload),
  previewFila: (dataInicio) => ipcRenderer.invoke('fila:preview', dataInicio),
  setFila: (payload) => ipcRenderer.invoke('fila:set', payload),
  getProject: (id, fila) => ipcRenderer.invoke('projects:get', id, fila),
  addProject: (payload) => ipcRenderer.invoke('projects:add', payload),
  getQueueProjects: (fila) => ipcRenderer.invoke('projects:getQueue', fila),
  moveProjectInQueue: (id, direction) => ipcRenderer.invoke('projects:moveInQueue', id, direction),
  reorderQueueProjects: (orderIds, fila) => ipcRenderer.invoke('projects:reorderQueue', orderIds, fila),
  resetQueueOrder: () => ipcRenderer.invoke('projects:resetQueueOrder'),
  updateProject: (id, patch) => ipcRenderer.invoke('projects:update', id, patch),
  removeProject: (id) => ipcRenderer.invoke('projects:remove', id),
  toggleChecklistToday: (id, done) => ipcRenderer.invoke('projects:toggleChecklistToday', id, done),
  toggleVideoToday: (id, done) => ipcRenderer.invoke('projects:toggleVideoToday', id, done),
  setTaskOnDate: (id, dateStr, task, done) => ipcRenderer.invoke('projects:setTaskOnDate', id, dateStr, task, done),
  markDeployDone: (id) => ipcRenderer.invoke('projects:markDeployDone', id),
  clearDeploy: (id) => ipcRenderer.invoke('projects:clearDeploy', id),
  setDeployToday: (id, done) => ipcRenderer.invoke('projects:setDeployToday', id, done),
  markMeetingDone: (id, dateStr, contexto, tipo) => ipcRenderer.invoke('projects:markMeetingDone', id, dateStr, contexto, tipo),
  scheduleMeeting: (id, payload) => ipcRenderer.invoke('meetings:schedule', id, payload),
  getAgendaMeetings: (dateStr) => ipcRenderer.invoke('meetings:getAgenda', dateStr),
  setMeetingDone: (meetingId, done) => ipcRenderer.invoke('meetings:setDone', meetingId, done),
  removeMeeting: (meetingId) => ipcRenderer.invoke('meetings:remove', meetingId),
  markEstimativaDone: (id) => ipcRenderer.invoke('projects:markEstimativaDone', id),
  clearEstimativa: (id) => ipcRenderer.invoke('projects:clearEstimativa', id),
  setEstimativaOnDate: (id, dateStr, done) => ipcRenderer.invoke('projects:setEstimativaOnDate', id, dateStr, done),
  markVideoDone: (id) => ipcRenderer.invoke('projects:markVideoDone', id),
  clearVideo: (id) => ipcRenderer.invoke('projects:clearVideo', id),
  addFoto: (id) => ipcRenderer.invoke('projects:addFoto', id),
  addFotoBytes: (id, fileName, bytes) => ipcRenderer.invoke('projects:addFotoBytes', id, fileName, bytes),
  removeFoto: (id, relPath) => ipcRenderer.invoke('projects:removeFoto', id, relPath),
  getBaseDir: () => ipcRenderer.invoke('projects:getBaseDir'),
});
